### PR TITLE
Use literalinclude to include schemas

### PR DESCRIPTION
**Pull request by saimn**
Hey @pllim ,

So using `literalinclude` to include the schemas in the rst docs, in a new page. It works quite well I think, the rendered page looks good (see below).

This must be referenced somewhere, I don't know how... Maybe the content of `io.misc.asdf` docstring should be moved in the rst docs as well ? Also we probably should include also the schemas for fits and units ?

Capture d’écran de 2019-04-28 00-32-24

### CODE REVIEW

**Comment by pllim** [comment]
Wow, this looks great indeed. Thanks!

> referenced somewhere

Yes, possibly can replace the `.. automodapi:: astropy.io.misc.asdf` part below in [misc.rst](https://github.com/astropy/astropy/blob/master/docs/io/misc.rst) with a reference to the new RST instead. But I am not sure if the rendered doc would look weird or not with the rest of the `io.misc` directives unchanged. 🤔  Another option is to move your new content straight into existing `misc.rst` instead of its own file?
```
.. automodapi:: astropy.io.misc

.. automodapi:: astropy.io.misc.hdf5

.. automodapi:: astropy.io.misc.yaml

.. automodapi:: astropy.io.misc.asdf
```

> include also the schemas for fits and units

I am actually not sure whether @drdavella excluded them on purpose or by accident. I guess it doesn't hurt to include them regardless, for completeness. So 👍 from me.

**Comment by pllim** [comment]
Please let me know how you wish to proceed. If you want to work on this more, I can wait to merge. Otherwise, I can also merge as-is and follow up when I get the chance. Thank you!

**Comment by saimn** [comment]
I moved the docstring to the rst docs, and added a link to the schemas page. I think it's quite good like this:

Capture d’écran de 2019-04-29 17-28-24

**Comment by pllim** [comment]
Oh, nice! I'll go ahead and merge this so I can check the CircleCI builds back in core. THANK YOU!

p.s. Are you satisfied with the build time now? 😄

**Comment by saimn** [comment]
> p.s. Are you satisfied with the build time now? 

Not really, it is still horribly slow ! Just a little better :wink:

**Comment by pllim** [comment]
But the bottleneck is somewhere else now? Or still on this page?

**Comment by saimn** [comment]
It is no more because of this page indeed, it is just that the docs are big and contain many examples and figures. And it is not easy to find if some doctest examples are slower than the average. One thing than could help a bit is to move the examples to the tutorials, which is planned I think?

**Comment by pllim** [comment]
> move the examples to the tutorials

There was a plan but I am not holding my breath... 😉 

Thanks again for the fix!

**Pull request merged**
